#!/usr/bin/env node
// Writes src/version.ts from package.json. Keeping it inside src/ means
// tsc can use rootDir: "./src" without reaching above for the JSON, and
// avoids the dist/esm/src/ nesting that an out-of-tree JSON import causes.
// Run automatically via the `prebuild*` npm scripts.

const fs = require('node:fs');
const path = require('node:path');

const pkg = require('../package.json');
const target = path.join(__dirname, '..', 'src', 'version.ts');
const body = `// AUTOGENERATED by scripts/sync-version.cjs — do not edit by hand.
export const VERSION = ${JSON.stringify(pkg.version)};
`;

const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
if (current !== body) {
  fs.writeFileSync(target, body);
}
